---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "appcat-service-s3.fullname" . }}-manager'
  labels:
    {{- include "appcat-service-s3.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - cloudscale.s3.appcat.vshn.io
    resources:
      - objectsusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudscale.s3.appcat.vshn.io
    resources:
      - objectsusers/finalizers
      - objectsusers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
