---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "provider-cloudscale.fullname" . }}-manager'
  labels:
    {{- include "provider-cloudscale.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - buckets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - buckets/finalizers
      - buckets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - objectsusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - objectsusers/finalizers
      - objectsusers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - providerconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - providerconfigs/finalizers
      - providerconfigs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - providerconfigusages
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudscale.crossplane.io
    resources:
      - providerconfigusages/finalizers
      - providerconfigusages/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
