apiVersion: cloudscale.crossplane.io/v1
kind: ObjectsUser
metadata:
  creationTimestamp: null
  name: my-cloudscale-user
spec:
  forProvider:
    secretRef:
      name: my-cloudscale-user-credentials
      namespace: default
    tags:
      key: value
  providerConfigRef:
    name: provider-config
status:
  atProvider: {}
