apiVersion: cloudscale.crossplane.io/v1
kind: ObjectsUser
metadata:
  creationTimestamp: null
  name: my-cloudscale-user
spec:
  forProvider:
    tags:
      key: value
  providerConfigRef:
    name: provider-config
  writeConnectionSecretToRef:
    name: my-cloudscale-user-credentials
    namespace: default
status:
  atProvider: {}
