# Default values for appcat-service-s3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- Operator image registry
  registry: ghcr.io
  # -- Operator image repository
  repository: vshn/appcat-service-s3
  # -- Operator image pull policy
  # If set to empty, then Kubernetes default behaviour applies.
  pullPolicy: IfNotPresent
  # -- Operator image tag
  tag: latest

operator:
  # -- Overrides arguments passed to the entrypoint
  args: []

tokens:
  # -- The cloudscale.ch API token
  cloudscale: ""
  # -- Name of the external secret if tokens are not managed by this chart.  
  # See `templates/secret.yaml` to figure out how to setup the expected environment variables.
  externalSecretName: ""

# -- List of image pull secrets if custom image is behind authentication.
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and `.create` is `true`, a name is generated using the fullname template
  name: ""

# -- Annotations to add to the Pod spec.
podAnnotations: {}

# -- Security context to add to the Pod spec.
podSecurityContext: {}
# fsGroup: 2000

# -- Container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Service type
  type: ClusterIP
  # -- Service port number
  port: 80
  # -- Annotations to add to the service
  annotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
